source: widowx_arm.yaml
port: /dev/ttyWIDOWX
read_rate: 50
write_rate: 50

joints: {
    joint_1: {id: 1, ticks: 4096, neutral: 2048, range: 360.0, max_speed: 100.0},
    joint_2: {id: 2, ticks: 4096, neutral: 2048, range: 360.0, max_speed: 100.0},
    joint_3: {id: 3, ticks: 4096, neutral: 2048, range: 360.0, max_speed: 100.0, invert: true},
    joint_4: {id: 4, ticks: 4096, neutral: 2048, range: 360.0, max_speed: 100.0, invert: true},
    joint_5: {id: 5, ticks: 1024, neutral: 512, range: 300.0, max_speed: 100.0, invert: true},
    # joint_6: {id: 6, ticks: 1024, neutral: 350, max_speed: 90, type: prismatic, radius: .0078, connector: .024, offset: .016}
    joint_6: {id: 6, ticks: 1024, neutral: 180, range: 2.0, max_speed: 90.0}
}
controllers: {
    arm_controller: {type: follow_controller, joints: [joint_1, joint_2, joint_3, joint_4, joint_5], action_name: arm_controller/follow_joint_trajectory, onboard: False },
}